import Head from "next/head";
export default function Home() {
  return (
    <div >
      <Head>
        <title>Jestor Nogueiro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       

        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com"/>
<link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet"/>

      </Head>
<div className="bg-gradient-to-r from-green to-blue-500">
  
  <h1>Portfolio</h1>
</div>
    </div>
  );
}
